# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addplan.ui'
#
# Created by: PySide2 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Addplan(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(184, 138)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(50, 25))
        self.label_2.setMaximumSize(QtCore.QSize(50, 25))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(100, 25))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(150, 25))
        self.label_3.setMaximumSize(QtCore.QSize(150, 25))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_limit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_limit.setMinimumSize(QtCore.QSize(100, 25))
        self.lineEdit_limit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_limit.setObjectName("lineEdit_limit")
        self.horizontalLayout_2.addWidget(self.lineEdit_limit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.checkbox_limit=QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_limit.setMinimumSize(QtCore.QSize(0, 25))
        self.checkbox_limit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.checkbox_limit.setObjectName("cbox_limit")
        self.verticalLayout.addWidget(self.checkbox_limit)
        self.pbtn_import = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_import.setMinimumSize(QtCore.QSize(0, 25))
        self.pbtn_import.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbtn_import.setObjectName("pbtn_import")
        self.verticalLayout.addWidget(self.pbtn_import)
        
        self.pbtn_OK = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_OK.setMinimumSize(QtCore.QSize(0, 25))
        self.pbtn_OK.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbtn_OK.setObjectName("pbtn_OK")
        self.verticalLayout.addWidget(self.pbtn_OK)
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "添加计划"))
        self.label.setText(_translate("MainWindow", "添加计划"))
        self.label_2.setText(_translate("MainWindow", "计划名："))
        self.label_3.setText(_translate("MainWindow", "限时（单位：分钟）："))
        self.pbtn_import.setText(_translate("MainWindow", "从本地文件导入"))
        self.pbtn_OK.setText(_translate("MainWindow", "OK"))
        self.checkbox_limit.setText(_translate("MainWindow", "限时完成"))
